name: Generate Diagram
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Pydeps
        run: |
          sudo apt-get install -y graphviz
          pip install pydeps

      - name: Generate Module Diagram
        run: pydeps src --noshow -o codebase.png --only src

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: codebase-diagrams
          path: "*.png"
